name: Node CI


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Use Node.js
uses: actions/setup-node@v4
with:
node-version: '18'
- name: Install backend deps
run: |
cd backend
npm ci
- name: Install frontend deps
run: |
cd frontend
npm ci
- name: Run backend tests (if any)
run: |
echo "No tests configured yet"
